### PR TITLE
Make an `EveryDictList` and `AllDictList`, based on eeue56/elm-all-dict

### PR DESCRIPTION
**Pull request by rgrempel**
To implement #12.

### CODE REVIEW

**Comment by rgrempel** [comment]
So, we now have an `AllDictList`. It's like `DictList`, but based on `AllDict` instead of `Dict`.

Essentially, I started by duplicating `DictList`, and then fixing the types etc. to adapt to `AllDict`. Of course, some function signatures now need you to provide the "ordering" function that `AllDict` requires.

So, then, what to do with the original `DictList`? It's a shame to have all that duplicated code, isn't it ...

Well, in principle, a `DictList` is now just a specialization of `AllDictList` -- that is, a specialization where the key itself is comparable. So, you could think of a `DictList` in this way:

```elm
type alias DictList k v =
    AllDictList k v k
```

And, if you do that, you can implement most of the `DictList` functions by simply saying that they are equal to the `AllDictList` versions. E.g.

```elm
indexedMap : (Int -> comparable -> a -> b) -> DictList comparable a -> DictList comparable b
indexedMap =
    AllDictList.indexedMap
```

What we provide in `DictList` is, for these functions, only a simplification of the type signature. (In fact, of course, you could just use `AllDictList.indexedMap` directly with a `DictList`, since a `DictList` is an `AllDictList`).

Where `AllDictList` requires an "ordering" function, we can just provide `identity` (since our type alias ensures that the key is also the comparable). E.g.

```elm
empty : DictList comparable v
empty =
    AllDictList.empty identity
```

Isn't that nice?

So, now we have `DictList` and `AllDictList`, with minimal code duplication.

And, even better, all the original tests for `DictList` still pass, without any changes to the tests, which is a good sign.

It ought to be possible to make an `EveryDictList` using a similar strategy, just using `toString` instead of `identity` as the ordering function.

**Comment by rgrempel** [comment]
You might find this interesting, @eeue56 -- and thanks for elm-all-dict!

**Comment by rgrempel** [comment]
So, I'll let this rest for a bit and then finish it up. I should go over the documentation and make sure it reads correctly, and write some tests for `EveryDictList`. In principle, the existing tests for `DictList` also test a fair bit of `AllDictList`, but perhaps there are a few `AllDictList`-specific tests that would be appropriate as well.

**Comment by amitaibu** [comment]
I have a use case for this in one of our new Elm projects, so I'd love to get it in when you get a chance :)

**Comment by rgrempel** [comment]
I've published this as version 2.0.0.

**Pull request merged**
